export type GameCategory =
  | "popular"
  | "acao"
  | "rpg"
  | "terror"
  | "luta"
  | "tiro";

export interface Game {
  id: string | number;
  name: string;
  originalPrice: string;
  discountedPrice: string;
  discount: string;
  cover: string;
  description: string;
  platform: string;
  minRequirements: string;
  recommendedRequirements: string;
  delivery: string;
  /** YouTube video ID used in the popular games trailer player */
  trailer?: string;
  categories: GameCategory[];
}

const steamHeader = (appId: number) =>
  `https://cdn.cloudflare.steamstatic.com/steam/apps/${appId}/header.jpg`;

const defaultDelivery =
  "Envio automático por e-mail em até 5 minutos após a confirmação do pagamento.";
const defaultPlatform = "PC";
const defaultMin =
  "OS: Windows 10, Processador: Intel Core i5, Memória: 8GB RAM, Placa de vídeo: GTX 1060";
const defaultRec =
  "OS: Windows 11, Processador: Intel Core i7, Memória: 16GB RAM, Placa de vídeo: RTX 3060";

export const games: Game[] = [
  {
    id: 1,
    name: "Resident Evil Requiem (CONTA OFFLINE)",
    originalPrice: "R$ 300,00",
    discountedPrice: "R$ 12,99",
    discount: "96% OFF",
    cover: steamHeader(1196590),
    description:
      "O novo capítulo da saga Resident Evil chega trazendo terror psicológico de tirar o fôlego, gráficos de última geração e uma atmosfera sombria como nunca antes.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "M7yEzlF7dPo",
    categories: ["popular", "terror"],
  },
  {
    id: 2,
    name: "Forza Horizon 6",
    originalPrice: "R$ 300,00",
    discountedPrice: "R$ 14,99",
    discount: "95% OFF",
    cover: steamHeader(1551360),
    description:
      "A próxima geração de Forza Horizon, com mundo aberto cinematográfico, centenas de carros e a melhor sensação de velocidade do gênero.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "FYH9n37B7Yw",
    categories: ["popular", "acao"],
  },
  {
    id: 3,
    name: "Crimson Desert (CONTA OFFLINE)",
    originalPrice: "R$ 350,00",
    discountedPrice: "R$ 14,99",
    discount: "96% OFF",
    cover: steamHeader(1601580),
    description:
      "Um RPG de ação épico em um mundo medieval brutal. Explore terras vastas, enfrente bestas colossais e forje sua lenda em Pywel.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "1bDS3eNcCwc",
    categories: ["popular", "rpg"],
  },
  {
    id: 4,
    name: "Baldur's Gate 3",
    originalPrice: "R$ 199,00",
    discountedPrice: "R$ 9,99",
    discount: "95% OFF",
    cover: steamHeader(1086940),
    description:
      "O aclamado RPG de fantasia da Larian Studios. Reúna sua party, faça escolhas marcantes e mergulhe em uma campanha lendária inspirada em D&D.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "OcP0WdH7rTs",
    categories: ["popular", "rpg"],
  },
  {
    id: 5,
    name: "Red Dead Redemption 2",
    originalPrice: "R$ 299,00",
    discountedPrice: "R$ 9,99",
    discount: "97% OFF",
    cover: steamHeader(1174180),
    description:
      "Uma épica história de honra e traição na decadência do Velho Oeste americano. A obra-prima da Rockstar Games.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "eaW0tYpxyp0",
    categories: ["popular", "tiro"],
  },
  {
    id: 6,
    name: "Red Dead Redemption 1",
    originalPrice: "R$ 250,00",
    discountedPrice: "R$ 9,99",
    discount: "96% OFF",
    cover: steamHeader(2668510),
    description:
      "O clássico que definiu o gênero western chega ao PC. Acompanhe John Marston em sua jornada de redenção no Velho Oeste.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "Quz0I5NgolY",
    categories: ["popular", "tiro"],
  },
  {
    id: 7,
    name: "Grand Theft Auto V Enhanced",
    originalPrice: "R$ 150,00",
    discountedPrice: "R$ 9,99",
    discount: "93% OFF",
    cover: steamHeader(3240220),
    description:
      "A versão definitiva de GTA V com ray tracing, melhorias visuais e suporte aos hardwares mais recentes. Los Santos como você nunca viu.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "QkkoHAzjnUs",
    categories: ["popular", "tiro"],
  },
  {
    id: 8,
    name: "Grand Theft Auto V Legacy",
    originalPrice: "R$ 150,00",
    discountedPrice: "R$ 9,99",
    discount: "93% OFF",
    cover: steamHeader(271590),
    description:
      "O fenômeno mundial da Rockstar. Viva a vida de três criminosos em Los Santos no clássico que vendeu mais de 200 milhões de cópias.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "QkkoHAzjnUs",
    categories: ["popular", "tiro"],
  },
  {
    id: 9,
    name: "The Last Of Us Parte 2",
    originalPrice: "R$ 200,00",
    discountedPrice: "R$ 9,99",
    discount: "95% OFF",
    cover: steamHeader(2531310),
    description:
      "Cinco anos após os eventos do primeiro jogo, Ellie embarca em uma jornada implacável de vingança em um mundo pós-apocalíptico.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "II-ZHaA_t9Q",
    categories: ["popular", "tiro"],
  },
  {
    id: 10,
    name: "The Last Of Us",
    originalPrice: "R$ 250,00",
    discountedPrice: "R$ 9,99",
    discount: "96% OFF",
    cover: steamHeader(1888930),
    description:
      "Joel e Ellie atravessam os Estados Unidos devastados em uma das histórias mais marcantes dos videogames. Edição PC remasterizada.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "WoOEz4FbDSc",
    categories: ["popular", "tiro"],
  },
  {
    id: 11,
    name: "Marvel's Spider-Man 2",
    originalPrice: "R$ 250,00",
    discountedPrice: "R$ 9,99",
    discount: "96% OFF",
    cover: steamHeader(2651280),
    description:
      "Peter Parker e Miles Morales unem forças contra Venom em uma Nova York maior, mais densa e cheia de surpresas.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "qWa9DnUWjhI",
    categories: ["acao"],
  },
  {
    id: 12,
    name: "Marvel's Spider-Man: Miles Morales",
    originalPrice: "R$ 200,00",
    discountedPrice: "R$ 9,99",
    discount: "95% OFF",
    cover: steamHeader(1817190),
    description:
      "Miles Morales descobre poderes que o diferenciam de seu mentor Peter Parker, em uma aventura inesquecível no coração de Harlem.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "5b4xhKkn58E",
    categories: ["acao"],
  },
  {
    id: 13,
    name: "Marvel's Spider-Man Remastered",
    originalPrice: "R$ 250,00",
    discountedPrice: "R$ 9,99",
    discount: "96% OFF",
    cover: steamHeader(1817070),
    description:
      "A aventura definitiva do Homem-Aranha com gráficos remasterizados, suporte a ray tracing e todos os DLCs inclusos.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "q4GgI7vNyo4",
    categories: ["acao"],
  },
  {
    id: 14,
    name: "God of War Ragnarök",
    originalPrice: "R$ 250,00",
    discountedPrice: "R$ 9,99",
    discount: "96% OFF",
    cover: steamHeader(2322010),
    description:
      "Kratos e Atreus enfrentam o Ragnarök e os Nove Reinos em uma jornada épica pela mitologia nórdica.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "EE-4GvjKcfs",
    categories: ["acao"],
  },
  {
    id: 15,
    name: "God of War",
    originalPrice: "R$ 200,00",
    discountedPrice: "R$ 9,99",
    discount: "95% OFF",
    cover: steamHeader(1593500),
    description:
      "Kratos retorna em uma reinvenção brutal da série, agora ambientada nas terras geladas dos deuses nórdicos.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "FXz-IY-7-Lk",
    categories: ["acao"],
  },
  {
    id: 16,
    name: "Ghost of Tsushima",
    originalPrice: "R$ 250,00",
    discountedPrice: "R$ 9,99",
    discount: "96% OFF",
    cover: steamHeader(2215430),
    description:
      "Em 1274, o samurai Jin Sakai enfrenta a invasão mongol da ilha de Tsushima em uma aventura visualmente deslumbrante.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "iwROgK94zcM",
    categories: ["acao"],
  },
  {
    id: 17,
    name: "SILENT HILL 2",
    originalPrice: "R$ 350,00",
    discountedPrice: "R$ 9,99",
    discount: "97% OFF",
    cover: steamHeader(2124490),
    description:
      "O remake do clássico de terror psicológico. James Sunderland retorna à cidade enevoada em busca de respostas perturbadoras.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "ttMOK5BPVqI",
    categories: ["terror"],
  },
  {
    id: 18,
    name: "Resident Evil 4",
    originalPrice: "R$ 200,00",
    discountedPrice: "R$ 9,99",
    discount: "95% OFF",
    cover: steamHeader(2050650),
    description:
      "O remake aclamado pela crítica. Leon S. Kennedy retorna a uma aldeia rural sinistra para resgatar a filha do presidente.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "Z8RKZ-EsvKM",
    categories: ["terror"],
  },
  {
    id: 19,
    name: "DRAGON BALL SPARKING ZERO",
    originalPrice: "R$ 290,00",
    discountedPrice: "R$ 9,99",
    discount: "97% OFF",
    cover: steamHeader(1790600),
    description:
      "A nova geração da série Budokai Tenkaichi. Mais de 180 personagens em batalhas espetaculares com gráficos impressionantes.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "5_xRDhSP0CY",
    categories: ["luta"],
  },
  {
    id: 20,
    name: "Hogwarts Legacy",
    originalPrice: "R$ 299,90",
    discountedPrice: "R$ 9,99",
    discount: "97% OFF",
    cover: steamHeader(990080),
    description:
      "Viva sua própria aventura no universo de Harry Potter. Frequente Hogwarts no século XIX e desvende um mistério ancestral.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "1O6Qstncpnc",
    categories: ["rpg"],
  },
  {
    id: 21,
    name: "Horizon Zero Dawn Complete Edition",
    originalPrice: "R$ 249,00",
    discountedPrice: "R$ 9,99",
    discount: "96% OFF",
    cover: steamHeader(1151640),
    description:
      "Aloy explora um mundo pós-apocalíptico dominado por máquinas. Edição completa com a expansão The Frozen Wilds.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "u4-FCsiF5x4",
    categories: ["acao"],
  },
  {
    id: 22,
    name: "Detroit Become Human",
    originalPrice: "R$ 199,00",
    discountedPrice: "R$ 9,99",
    discount: "95% OFF",
    cover: steamHeader(1222140),
    description:
      "Em um futuro próximo, androides ganham consciência. Suas escolhas definem o destino de três personagens em um mundo à beira do colapso.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "Ka4yhoZSXgU",
    categories: ["acao"],
  },
  {
    id: 23,
    name: "Mortal Kombat 11",
    originalPrice: "R$ 229,99",
    discountedPrice: "R$ 9,99",
    discount: "96% OFF",
    cover: steamHeader(976310),
    description:
      "O retorno violento do icônico jogo de luta. Fatalities cinemáticos, roster expandido e modo história envolvente.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "TGUEqbcs8r4",
    categories: ["luta"],
  },
  {
    id: 24,
    name: "Cyberpunk 2077",
    originalPrice: "R$ 200,00",
    discountedPrice: "R$ 9,99",
    discount: "95% OFF",
    cover: steamHeader(1091500),
    description:
      "Um RPG de mundo aberto em Night City, uma metrópole obcecada por poder, glamour e modificações corporais.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "8X2kIfS6fb8",
    categories: ["rpg"],
  },
  {
    id: 25,
    name: "UNCHARTED: Coleção Legado dos Ladrões",
    originalPrice: "R$ 260,00",
    discountedPrice: "R$ 9,99",
    discount: "96% OFF",
    cover: steamHeader(1659420),
    description:
      "Inclui Uncharted 4: A Thief's End e Uncharted: The Lost Legacy. Aventura cinematográfica em busca de tesouros esquecidos.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "RvCFW7XPwBs",
    categories: ["acao"],
  },
  {
    id: 26,
    name: "171",
    originalPrice: "R$ 59,99",
    discountedPrice: "R$ 9,99",
    discount: "83% OFF",
    cover: steamHeader(1284190),
    description:
      "O GTA brasileiro. Explore uma fictícia cidade tupiniquim cheia de personagens icônicos, missões e humor genuinamente nacional.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "VvWXboS8X3I",
    categories: ["acao"],
  },
  {
    id: 27,
    name: "Elden Ring",
    originalPrice: "R$ 275,00",
    discountedPrice: "R$ 9,99",
    discount: "96% OFF",
    cover: steamHeader(1245620),
    description:
      "O épico Soulslike da FromSoftware em parceria com George R. R. Martin. Explore as Terras Intermédias em busca da Runa Maior.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "E3Huy2cdih0",
    categories: ["rpg"],
  },
  {
    id: 28,
    name: "Little Nightmares III",
    originalPrice: "R$ 180,00",
    discountedPrice: "R$ 9,99",
    discount: "94% OFF",
    cover: steamHeader(2511660),
    description:
      "Low e Alone exploram a sinistra Espiral em uma aventura cooperativa cheia de quebra-cabeças e criaturas grotescas.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "u_uM6Cmd-1U",
    categories: ["terror"],
  },
  {
    id: 29,
    name: "Hollow Knight: Silksong",
    originalPrice: "R$ 60,00",
    discountedPrice: "R$ 9,99",
    discount: "83% OFF",
    cover: steamHeader(1030300),
    description:
      "A muito aguardada sequência de Hollow Knight. Jogue como Hornet em um reino exuberante e perigoso, repleto de inimigos e segredos.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "pFAknD_9U7c",
    categories: ["rpg"],
  },
  {
    id: 30,
    name: "Dying Light The Beast",
    originalPrice: "R$ 250,00",
    discountedPrice: "R$ 9,99",
    discount: "96% OFF",
    cover: steamHeader(3008130),
    description:
      "Kyle Crane retorna em uma nova aventura de parkour e sobrevivência contra hordas de infectados em um mundo aberto brutal.",
    platform: defaultPlatform,
    minRequirements: defaultMin,
    recommendedRequirements: defaultRec,
    delivery: defaultDelivery,
    trailer: "1JfdJ_BKQjE",
    categories: ["terror"],
  },
];
