/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StreamingIdRouteImport } from './routes/streaming.$id'
import { Route as GameIdRouteImport } from './routes/game.$id'

const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamingIdRoute = StreamingIdRouteImport.update({
  id: '/streaming/$id',
  path: '/streaming/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdRoute = GameIdRouteImport.update({
  id: '/game/$id',
  path: '/game/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/game/$id': typeof GameIdRoute
  '/streaming/$id': typeof StreamingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/game/$id': typeof GameIdRoute
  '/streaming/$id': typeof StreamingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/game/$id': typeof GameIdRoute
  '/streaming/$id': typeof StreamingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/busca' | '/game/$id' | '/streaming/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/busca' | '/game/$id' | '/streaming/$id'
  id: '__root__' | '/' | '/busca' | '/game/$id' | '/streaming/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscaRoute: typeof BuscaRoute
  GameIdRoute: typeof GameIdRoute
  StreamingIdRoute: typeof StreamingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaming/$id': {
      id: '/streaming/$id'
      path: '/streaming/$id'
      fullPath: '/streaming/$id'
      preLoaderRoute: typeof StreamingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$id': {
      id: '/game/$id'
      path: '/game/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof GameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscaRoute: BuscaRoute,
  GameIdRoute: GameIdRoute,
  StreamingIdRoute: StreamingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
